format = """
[  ](bg:#C0A36E fg:#1F1F28)\
$directory\
$nodejs\
$rust\
$php\
$c\
$python\
$git_metrics\
$git_branch\
$character"""

[character]
success_symbol = "[](fg:#E6C384)"
error_symbol = "[](fg:#E6C384)"

[c]
symbol = ""
version_format = " v${major}"
format = '[[ $symbol($version) ](fg:#1F1F28 bg:#727169)]($style)'

[directory]
style = "fg:#1F1F28 bg:#E6C384"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#1F1F28 bg:#E6C384)]($style)'

[git_metrics]
disabled = false
format = '[[+$added](fg:#76946A bg:#E6C384)/[-$deleted](fg:#C34043 bg:#E6C384)](fg:#1F1F28 bg:#E6C384)'

[nodejs]
symbol = ""
version_format = " v${major}"
format = '[[ $symbol($version) ](fg:#1F1F28 bg:#98BB6C)]($style)'

[rust]
symbol = ""
version_format = " v${major}.${minor}"
format = '[[ $symbol($version) ](fg:#1F1F28 bg:#C34043)]($style)'

[php]
symbol = ""
version_format = " v${major}.${minor}"
format = '[[ $symbol($version) ](fg:#1F1F28 bg:#957FB8)]($style)'

[python]
symbol = ""
version_format = " v${major}.${minor}"
format = "[[ $symbol($version) ($virtualenv )](fg:#1F1F28 bg:#7E9CD8)]($style)"

[cmd_duration]
format = "took [$duration]($style)"
min_time_to_notify = 100
